title: Vincent Lefoulon (Vayel)
description: French student in computer science, who enjoys deep learning, philosophy, climbing and meditation.
theme: jekyll-theme-tactile
linkedin_url: https://www.linkedin.com/in/vincent-lefoulon-87bb1310a/
zestedesavoir_url: https://zestedesavoir.com/membres/voir/Vayel/
kaggle_url: https://www.kaggle.com/vincentlefoulon

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ":categories/:slug/"
  - scope:
      path: "assets/img"
    values:
      image: true
