title: Vincent Lefoulon (Vayel)
description: Looking for a 6-month internship from February 2018 in deep learning, preferably abroad. 
theme: jekyll-theme-tactile
linkedin_url: https://www.linkedin.com/in/vincent-lefoulon-87bb1310a/
zestedesavoir_url: https://zestedesavoir.com/membres/voir/Vayel/
kaggle_url: https://www.kaggle.com/vincentlefoulon

defaults:
  - scope:
      path: "" # All files
    values:
      layout: "default"
  - scope:
      path: "assets/img"
    values:
      image: true
